-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) YEAR, MONTH(OS.SALES_DATE) MONTH,UI.GENDER,COUNT(distinct(UI.USER_ID)) USERS
FROM ONLINE_SALE OS,USER_INFO UI
WHERE UI.GENDER IS NOT NULL AND OS.USER_ID = UI.USER_ID
GROUP BY YEAR(OS.SALES_DATE),MONTH(OS.SALES_DATE),GENDER
ORDER BY YEAR(OS.SALES_DATE) ASC,MONTH(OS.SALES_DATE) ASC,GENDER ASC;