-- 코드를 입력하세요
SELECT DISTINCT(CI2.CART_ID) FROM CART_PRODUCTS CI2,
(SELECT DISTINCT(CART_ID) FROM CART_PRODUCTS
WHERE NAME = 'MILK') CI
WHERE CI2.NAME = 'YOGURT' AND CI.CART_ID = CI2.CART_ID
ORDER BY CI2.CART_ID;
