SELECT RI.FOOD_TYPE,RI.REST_ID,RI.REST_NAME,RI.FAVORITES
FROM REST_INFO RI,
(SELECT FOOD_TYPE,MAX(FAVORITES) FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE) MX
WHERE MX.FAVORITES = RI.FAVORITES AND MX.FOOD_TYPE = RI.FOOD_TYPE
ORDER BY FOOD_TYPE DESC;
# ORDER BY FOOD_TYPE DESC,FAVORITES DESC;