SELECT RI.FOOD_TYPE,RI.REST_ID,RI.REST_NAME,RI.FAVORITES
FROM REST_INFO RI,
(SELECT REST_ID,FOOD_TYPE,MAX(FAVORITES) FAVORITES FROM REST_INFO
GROUP BY FOOD_TYPE) MX
WHERE MX.FOOD_TYPE = RI.FOOD_TYPE AND
MX.FAVORITES = RI.FAVORITES
ORDER BY FOOD_TYPE DESC;