-- 코드를 입력하세요

SELECT RI.FOOD_TYPE,REST_ID,REST_NAME,RI.FAVORITES FROM REST_INFO RI,
(SELECT FOOD_TYPE,MAX(FAVORITES) AS FAVORITES FROM REST_INFO
GROUP BY FOOD_TYPE) MX
WHERE  RI.FAVORITES = MX.FAVORITES AND MX.FOOD_TYPE = RI.FOOD_TYPE
ORDER BY FOOD_TYPE DESC;
