SELECT MONTH(CR.START_DATE) MONTH,CR.CAR_ID,COUNT(CR.CAR_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CR,
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY CAR_ID
HAVING COUNT(CAR_ID) >= 5) S
WHERE MONTH(START_DATE) BETWEEN 8 AND 10 AND CR.CAR_ID = S.CAR_ID
GROUP BY CR.CAR_ID,MONTH(CR.START_DATE)
HAVING COUNT(CR.CAR_ID) > 0
ORDER BY MONTH ASC,CAR_ID DESC;
