-- 코드를 입력하세요 
SELECT FP.CATEGORY,FP.PRICE,FP.PRODUCT_NAME FROM FOOD_PRODUCT FP,
(SELECT CATEGORY,MAX(PRICE) AS PRICE FROM FOOD_PRODUCT
WHERE CATEGORY IN ('국','김치','식용유','과자')
GROUP BY CATEGORY) AS MX 
WHERE FP.PRICE = MX.PRICE AND MX.CATEGORY = FP.CATEGORY
GROUP BY CATEGORY
ORDER BY FP.PRICE DESC;