-- 코드를 입력하세요
SELECT PLACES.ID,PLACES.NAME,PLACES.HOST_ID FROM PLACES,
(SELECT HOST_ID FROM PLACES
GROUP BY HOST_ID
HAVING COUNT(ID) >= 2) HEAVY
WHERE PLACES.HOST_ID = HEAVY.HOST_ID
ORDER BY PLACES.ID;