-- 코드를 입력하세요
SELECT DISTINCT(CC.CAR_ID) FROM CAR_RENTAL_COMPANY_CAR CC,CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
WHERE CC.CAR_ID = RH.CAR_ID AND CC.CAR_TYPE ='세단' AND RH.START_DATE LIKE '%-10-%'
ORDER BY CC.CAR_ID DESC;
