-- 코드를 입력하세요
SELECT RN.REST_ID,RN.REST_NAME,RN.FOOD_TYPE,RN.FAVORITES,RN.ADDRESS,ROUND(AVG(RR.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO RN,REST_REVIEW RR
WHERE RN.REST_ID = RR.REST_ID AND RN.ADDRESS LIKE '서울%' AND RR.REVIEW_SCORE IS NOT NULL
GROUP BY RN.REST_ID
ORDER BY SCORE DESC,RN.FAVORITES DESC;